'use client';
import { useMemo } from 'react';
import { computeSldData } from '@/lib/solar/sld';
import type { DesignResult, SiteConfig } from '@/lib/solar/types';

const INK = '#0b1526';
const LINE = '#1e293b';
const MUTE = '#64748b';

function Box({ x, y, w, h, label, sub }: { x: number; y: number; w: number; h: number; label: string; sub?: string }) {
  return (
    <g>
      <rect x={x} y={y} width={w} height={h} fill="#fff" stroke={LINE} strokeWidth={1.5} />
      <text x={x + w / 2} y={y + h / 2 - (sub ? 4 : -4)} textAnchor="middle" fontSize={11} fontWeight={700} fill={INK}>{label}</text>
      {sub && <text x={x + w / 2} y={y + h / 2 + 12} textAnchor="middle" fontSize={9.5} fill={MUTE}>{sub}</text>}
    </g>
  );
}

// Breaker symbol: a small square with a diagonal strike, per single-line convention.
function Breaker({ x, y, label }: { x: number; y: number; label: string }) {
  return (
    <g>
      <rect x={x - 9} y={y - 9} width={18} height={18} fill="#fff" stroke={LINE} strokeWidth={1.5} />
      <line x1={x - 6} y1={y + 6} x2={x + 6} y2={y - 6} stroke={LINE} strokeWidth={1.5} />
      <text x={x} y={y - 15} textAnchor="middle" fontSize={9} fontWeight={700} fill={INK}>{label}</text>
    </g>
  );
}

// Disconnect switch symbol: circle-line-circle with an open blade.
function Disconnect({ x, y, label }: { x: number; y: number; label: string }) {
  const r = 2.5;
  return (
    <g>
      <circle cx={x - 12} cy={y} r={r} fill={LINE} />
      <circle cx={x + 12} cy={y} r={r} fill={LINE} />
      <line x1={x - 10} y1={y} x2={x + 8} y2={y - 9} stroke={LINE} strokeWidth={1.5} />
      <text x={x} y={y - 14} textAnchor="middle" fontSize={9} fontWeight={700} fill={INK}>{label}</text>
    </g>
  );
}

// Grounding symbol hung off a short stub below a box corner — kept clear of box labels.
function Ground({ x, y }: { x: number; y: number }) {
  return (
    <g stroke={LINE} strokeWidth={1.3}>
      <line x1={x} y1={y} x2={x} y2={y + 8} />
      <line x1={x - 9} y1={y + 8} x2={x + 9} y2={y + 8} />
      <line x1={x - 6} y1={y + 12} x2={x + 6} y2={y + 12} />
      <line x1={x - 3} y1={y + 16} x2={x + 3} y2={y + 16} />
    </g>
  );
}

function Wire({ points }: { points: [number, number][] }) {
  return <polyline points={points.map((p) => p.join(',')).join(' ')} fill="none" stroke={LINE} strokeWidth={1.5} />;
}

export default function SldDiagram({ design, site }: { design: DesignResult; site: SiteConfig }) {
  const sld = useMemo(() => computeSldData(design, site), [design, site]);
  const panelSymbols = Math.min(sld.arrayConfig.parallelStrings, 3);
  const arrayBottom = 40 + panelSymbols * 24;

  return (
    <div className="card p-4">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div>
          <h3 className="font-display text-sm font-bold text-ink">Single-line diagram (SLD)</h3>
          <p className="text-xs text-ink-faint">Engineering-style wiring overview with conductor sizes, breaker ratings and disconnect points.</p>
        </div>
        <button type="button" onClick={() => window.print()} className="btn-ghost !py-2 text-xs">
          🖨️ Print SLD
        </button>
      </div>

      <div id="sld-print-area" className="rounded-xl border border-surface-line bg-white p-3">
        <div className="mb-2 flex flex-wrap items-baseline justify-between gap-2 border-b border-surface-line pb-2">
          <div>
            <p className="font-display text-sm font-bold text-ink">{site.clientName || 'Untitled client'} — Single-Line Diagram</p>
            <p className="text-[11px] text-ink-faint">{site.siteName || 'Site not specified'} · {site.systemType.replace('_', '-')} system, {site.systemVoltage}V DC bus</p>
          </div>
          <p className="text-[11px] text-ink-faint">Generated by SmartTech Solar Calculator · {new Date().toLocaleDateString()}</p>
        </div>

        <svg viewBox="0 0 1000 360" className="w-full min-w-[860px]" role="img" aria-label="Single-line electrical diagram">
          {/* PV array */}
          <g>
            {Array.from({ length: panelSymbols }).map((_, i) => (
              <rect key={i} x={40} y={40 + i * 24} width={54} height={16} fill="#fff7ed" stroke="#ea580c" strokeWidth={1.3} />
            ))}
            <text x={67} y={arrayBottom + 14} textAnchor="middle" fontSize={9.5} fontWeight={700} fill={INK}>PV ARRAY</text>
            <text x={67} y={arrayBottom + 27} textAnchor="middle" fontSize={9} fill={MUTE}>{design.panelCount} × {design.panel.wattage}W</text>
            <text x={67} y={arrayBottom + 39} textAnchor="middle" fontSize={9} fill={MUTE}>
              {sld.arrayConfig.seriesCount}S{sld.arrayConfig.parallelStrings}P · Voc {sld.arrayConfig.stringVoc.toFixed(0)}V
            </text>
          </g>

          <Wire points={[[100, 90], [160, 90]]} />
          <Disconnect x={130} y={90} label="DC DISC" />
          <Wire points={[[148, 90], [210, 90]]} />
          <Breaker x={190} y={90} label={`${sld.dcArrayBreakerA}A`} />
          <text x={190} y={105} textAnchor="middle" fontSize={8.5} fill={MUTE}>{sld.dcCableSizeMm2}mm²</text>

          {sld.hasController ? (
            <>
              {/* Series topology: PV -> Controller -> Battery -> Inverter */}
              <Wire points={[[210, 90], [260, 90]]} />
              <Box x={260} y={65} w={100} h={50} label="CHARGE CTRL" sub={`${design.controller!.type} · ${design.chargeCurrentA.toFixed(0)}A`} />
              <Wire points={[[360, 90], [410, 90]]} />
              <Box x={410} y={65} w={110} h={50} label="BATTERY BANK" sub={`${design.batteryTotalCount} × ${design.battery.voltage}V ${design.battery.ah}Ah`} />
              <Ground x={425} y={115} />
              <Wire points={[[465, 115], [465, 160]]} />
              <Breaker x={465} y={160} label={`${sld.dcBatteryBreakerA}A`} />
              <text x={480} y={175} fontSize={8.5} fill={MUTE}>{sld.dcCableSizeMm2}mm²</text>
              <Wire points={[[465, 169], [465, 205]]} />
              <Box x={410} y={205} w={130} h={55} label="INVERTER" sub={`${design.inverter.model} · ${((design.inverter.continuousW * design.inverterCount) / 1000).toFixed(1)}kW`} />
              <Wire points={[[540, 232], [590, 232]]} />
              <Breaker x={590} y={232} label={`${sld.acMainBreakerA}A`} />
              <text x={590} y={247} textAnchor="middle" fontSize={8.5} fill={MUTE}>{sld.acCableSizeMm2}mm²</text>
              <Wire points={[[599, 232], [650, 232]]} />
              <Disconnect x={650} y={232} label="AC DISC" />
              <Wire points={[[662, 232], [790, 232], [790, 290]]} />
              <Box x={700} y={290} w={180} h={44} label="DISTRIBUTION PANEL" sub={`${(design.peakLoadW / 1000).toFixed(2)}kW peak load`} />
              <Ground x={715} y={334} />
              {sld.hasGrid && (
                <>
                  <Box x={735} y={140} w={110} h={44} label="UTILITY GRID" sub={`Meter · $${site.tariffUsdPerKwh.toFixed(2)}/kWh`} />
                  <Wire points={[[790, 184], [790, 232]]} />
                </>
              )}
            </>
          ) : sld.hasBattery ? (
            <>
              {/* Parallel topology: PV and Battery each feed the inverter's own MPPT / battery input */}
              <Wire points={[[210, 90], [650, 90], [650, 140]]} />
              <Box x={580} y={140} w={130} h={55} label="INVERTER" sub={`${design.inverter.model} · ${((design.inverter.continuousW * design.inverterCount) / 1000).toFixed(1)}kW`} />
              <Box x={380} y={140} w={110} h={55} label="BATTERY BANK" sub={`${design.batteryTotalCount} × ${design.battery.voltage}V ${design.battery.ah}Ah`} />
              <Ground x={395} y={195} />
              <Wire points={[[490, 167], [520, 167]]} />
              <Breaker x={520} y={167} label={`${sld.dcBatteryBreakerA}A`} />
              <text x={520} y={182} textAnchor="middle" fontSize={8.5} fill={MUTE}>{sld.dcCableSizeMm2}mm²</text>
              <Wire points={[[529, 167], [580, 167]]} />
              <Wire points={[[710, 167], [750, 167]]} />
              <Breaker x={750} y={167} label={`${sld.acMainBreakerA}A`} />
              <text x={750} y={182} textAnchor="middle" fontSize={8.5} fill={MUTE}>{sld.acCableSizeMm2}mm²</text>
              <Wire points={[[759, 167], [800, 167]]} />
              <Disconnect x={800} y={167} label="AC DISC" />
              <Wire points={[[812, 167], [850, 167], [850, 230]]} />
              <Box x={760} y={230} w={180} h={44} label="DISTRIBUTION PANEL" sub={`${(design.peakLoadW / 1000).toFixed(2)}kW peak load`} />
              <Ground x={775} y={274} />
              {sld.hasGrid && (
                <>
                  <Box x={790} y={60} w={110} h={44} label="UTILITY GRID" sub={`Meter · $${site.tariffUsdPerKwh.toFixed(2)}/kWh`} />
                  <Wire points={[[845, 104], [845, 167]]} />
                </>
              )}
            </>
          ) : (
            <>
              {/* Grid-tied, no battery: PV -> Inverter -> AC -> Grid (primary) / Loads */}
              <Wire points={[[210, 90], [580, 90]]} />
              <Box x={580} y={65} w={130} h={55} label="INVERTER" sub={`${design.inverter.model} · ${((design.inverter.continuousW * design.inverterCount) / 1000).toFixed(1)}kW`} />
              <Wire points={[[710, 92], [750, 92]]} />
              <Breaker x={750} y={92} label={`${sld.acMainBreakerA}A`} />
              <text x={750} y={107} textAnchor="middle" fontSize={8.5} fill={MUTE}>{sld.acCableSizeMm2}mm²</text>
              <Wire points={[[759, 92], [800, 92]]} />
              <Disconnect x={800} y={92} label="AC DISC" />
              <Wire points={[[812, 92], [850, 92], [850, 155]]} />
              <Box x={760} y={155} w={180} h={44} label="DISTRIBUTION PANEL" sub={`${(design.peakLoadW / 1000).toFixed(2)}kW peak load`} />
              <Ground x={775} y={199} />
              <Box x={790} y={20} w={110} h={40} label="UTILITY GRID" sub={`Meter · $${site.tariffUsdPerKwh.toFixed(2)}/kWh`} />
              <Wire points={[[845, 60], [845, 92]]} />
            </>
          )}
        </svg>

        <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 border-t border-surface-line pt-2 text-[10.5px] text-ink-faint">
          <span>⊗ Breaker/fuse (rated amperage shown)</span>
          <span>○–○ Disconnect switch</span>
          <span>⏚ Grounding/earthing point</span>
        </div>

        <p className="mt-2 text-[10.5px] leading-relaxed text-ink-faint">
          Indicative single-line diagram only — string voltage limits, breaker ratings and conductor sizes are
          simplified planning estimates{sld.arrayConfig.maxVoltageSource === 'assumed' ? ' (assumed max PV input voltage — verify against the selected inverter datasheet)' : ''}.
          Final circuit design, overcurrent protection, disconnect placement and grounding must be verified by a
          licensed electrician against the equipment datasheets and local electrical code before installation.
        </p>
      </div>
    </div>
  );
}
