// Real course content, grounded in "Become a Certified CCTV Technician"
// (the SmartTech Academy companion book). Replaces the placeholder
// contentHtml / quiz questions / assignment briefs the original seed
// shipped with, keyed by exact lesson/quiz/assignment title so
// backfillLessonContent() (see seed.mjs) can update rows on an
// already-seeded database without touching users, enrollments or payments.
//
// Coverage note: the book's table of contents lists 13 chapters, but only
// chapters 1-10 have actually been written so far — chapters 11
// (Troubleshooting and Maintenance), 12 (Running a CCTV Business) and 13
// (The Final Practical Assessment) exist as titles only. Course Modules
// 11-13 are left on their original placeholder content below until those
// chapters are written.

export const LESSON_CONTENT = {
  // ---- Module 1 — Introduction ----
  'Your toolkit as an installer': `
    <p>A site survey needs little more than eyes, a notebook and a torch, but the install itself needs a properly equipped van. Arriving without the right tool for a job — and having to leave to buy or fetch one — is the mark of an amateur, not a professional.</p>
    <p>Five categories cover almost everything: hand &amp; power tools (cordless drill/driver, screwdrivers, cable ties, a fish tape for routing through walls, a silicone gun for weatherproofing); termination tools (an RJ45 crimping tool, a BNC compression tool, a punch-down tool if you use patch panels); testing &amp; configuration gear (a network cable tester, a dedicated CCTV/camera tester, a multimeter, a laptop or phone with the manufacturer's app); access &amp; measurement tools (a ladder or tower rated for the surveyed height, a spirit level, a tape measure, a torch); and labelling &amp; documentation (a label maker, your site assessment report and bill of quantities, a camera to photograph the finished install).</p>`,

  // ---- Module 2 — CCTV Fundamentals (Chapter 1) ----
  'What is a CCTV system?': `
    <p>CCTV stands for Closed-Circuit Television. The defining word is "closed". Ordinary broadcast television distributes one signal openly to millions of anonymous receivers; a closed circuit confines the signal to a private loop of known, authorised endpoints — specific monitors, recorders and credentialed users. Nothing leaves that loop without permission.</p>
    <p>Every deployment, in every sector, comes back to protecting just four things — the framework this course keeps returning to: <strong>People</strong> (staff, customers, the public), <strong>Property</strong> (stock, cash, equipment, buildings), <strong>Process</strong> (how the organisation runs) and <strong>Proof</strong> (reliable, time-stamped evidence). A bank leads with Proof; a factory leads with Process; a hospital balances all four. The equipment always follows the priorities — never the other way around.</p>`,
  'Signal flow: camera to screen': `
    <p>Whatever family of system you build — analogue, IP or wireless — it is the same five-link chain: <strong>capture</strong> (the camera), <strong>carry</strong> (the cable or radio link), <strong>record</strong> (the DVR/NVR), <strong>store</strong> (the hard drive) and <strong>view</strong> (the monitor or app), with power running throughout. Learn this chain once and you understand every family — you are only ever swapping the hardware in each link.</p>
    <p>CCTV also has a history worth knowing: Era One (1942-1950s) was pure observation — the first system was built at Peenemünde to watch a rocket launch safely. Era Two (1960s-2000s) added security and evidence, as street cameras, the DVR and the internet arrived. Era Three (2010-present) is intelligence — today's systems detect, recognise and flag risk before it happens. The industry has moved from reactive, to proactive, to predictive.</p>`,

  // ---- Module 3 — Camera Types (Chapters 2 & 5) ----
  'Camera form factors explained': `
    <p>Six physical designs cover almost every job. The <strong>bullet</strong> camera is a visible, directional deterrent with a long infrared range, good for a driveway or fence line. The <strong>dome</strong> hides its aim inside a tamper-resistant housing — discreet and vandal-resistant, suited to shop ceilings. The <strong>PTZ</strong> (pan-tilt-zoom) covers a large area from one mount and can zoom into fine detail, at the cost of only ever recording one direction at a time. The <strong>fisheye</strong> captures a full 360° room in one ceiling-mounted unit — genuinely replacing several ordinary cameras. The <strong>thermal</strong> camera sees heat, not light — perfect for perimeter detection in total darkness, but useless for identifying who crossed the line. And the <strong>full-colour / ColorVu-type</strong> camera keeps recording in real colour after dark using a white-light illuminator, rather than falling back to grainy infrared.</p>`,
  'Analogue vs IP cameras': `
    <p>There are three families, and they all put video on a screen but carry the signal in fundamentally different ways. <strong>Analogue</strong> sends a continuous electrical waveform down coax to a DVR, which digitises it — cheap, simple, reliable, still very much alive thanks to HD-over-coax standards like AHD/HD-TVI/HD-CVI. <strong>IP</strong> cameras are small self-contained computers that digitise the image on-board and send network packets over Cat6 to an NVR, usually powered by PoE on the very same cable — the highest quality and now the professional default. <strong>Wireless</strong> carries the data link over radio instead of a cable — but "wireless" only ever refers to the data, not the power; the camera still needs mains or battery power at its location.</p>
    <p>The classic trap: two buildings 50 m apart, cameras on one monitored from the other. Running bare copper between separate buildings is a lightning and surge magnet that can destroy a recorder in one strike. The professional answer keeps copper inside each building and bridges the gap with a wireless link or fibre instead.</p>`,
  'Resolution, lenses & IR': `
    <p>Every camera datasheet lists the same handful of specs: <strong>megapixels</strong> (2MP/1080p up to 4MP, 5MP, 8MP/4K — more detail, more storage needed), <strong>frame rate</strong> (15-30 FPS for CCTV), <strong>WDR</strong> (keeps detail visible in both bright and dark parts of the same scene), <strong>bitrate/compression</strong> (H.265 roughly halves H.264's file size at the same quality), <strong>infrared range</strong> (20m on small cameras up to 40-60m+ on larger units), and <strong>IP rating</strong> — IP66 for standard outdoor exposure, IP67 where temporary submersion is possible.</p>
    <p>The lens decides how wide an area the camera sees and how much detail it resolves at distance — a wide lens covering a whole car park will never resolve a face, however many megapixels the sensor has. A 2.8mm lens gives roughly 110° for wide room coverage; 4mm (~90°) is the general-purpose default; 6mm (~53°) suits a corridor or driveway; 8mm (~40°) zooms in on one specific point like a gate or till. Varifocal and motorised lenses let you fine-tune the field of view on site rather than being locked into a fixed factory setting.</p>`,

  // ---- Module 4 — DVR & NVR (Chapter 3) ----
  'DVR vs NVR': `
    <p>A <strong>DVR</strong> is built for analogue cameras: each camera arrives over its own BNC coax connection carrying a raw analogue waveform, and the DVR itself digitises, compresses (H.264/H.265) and stores it — the camera does none of that work, which is why analogue cameras are cheap. An <strong>NVR</strong> is built for IP cameras: because the camera already digitises and compresses its own image, the NVR's job is lighter — receive the finished network stream, record it, manage playback — and most NVRs include built-in PoE ports so one box both powers and records a whole bank of cameras. A <strong>hybrid ("Penta-brid")</strong> recorder bridges both worlds on the same unit — useful for a client upgrading gradually from analogue to IP, but rarely the cheapest choice on a brand-new single-family install.</p>`,
  'Hard drive & storage sizing': `
    <p>CCTV storage is almost always a surveillance-rated hard disk drive (lines like Western Digital Purple or Seagate SkyHawk), not a desktop drive or an SSD — built and warrantied for continuous 24/7 writing. Sizing comes down to four factors: the bitrate each camera streams, the number of channels, the retention period the client (or the law) needs, and whether recording is continuous or motion-only.</p>
    <p>Rough formula: storage (GB) ≈ bitrate (Mbps) × 86,400 seconds/day × retention days × channels ÷ 8 ÷ 1,000. Worked example: 4 cameras at 4 Mbps each, 30 days' continuous retention → roughly 5,184 GB, so plan for a 6TB drive with room to spare. Always round up — a drive that fills two days early has already failed the client.</p>`,

  // ---- Module 5 — Cabling (Chapter 7) ----
  'Coaxial cable & BNC termination': `
    <p>Most CCTV coax sold today is "Siamese" cable — the coax core bonded to a separate 2-core power cable in one jacket, so a single pull carries both video and power. RG6 has a thicker centre conductor than RG59 and suffers less loss over distance, making it the better choice for longer runs.</p>
    <p>Three ways to fit a BNC connector: twist-on (fast, tool-free, but loosens over time — avoid beyond a quick test); crimp-on (a coax stripper plus a crimping tool — secure and the most widely taught method); and compression (a stripper plus a compression tool — the best weatherproofing and pull-strength of the three, and the professional default for any outdoor run). Whichever method, inspect the braided shield on every single termination — a nicked or loose shield can still show a picture on the bench and then fail intermittently once exposed to real electrical noise on site.</p>`,
  'Cat6 & RJ45 termination': `
    <p>T568A and T568B both work identically — the only difference is the orange and green pairs swap at pins 1-2 and 3-6. What matters is consistency: mixing standards within one run, or between a plug and the jack it terminates into, is a genuine, common cause of "the camera won't connect" call-outs. This book uses T568B throughout, as do most commercial installers.</p>
    <p>Terminating an RJ45 plug: strip ~30mm of jacket without nicking the pairs inside, untwist each pair only as far as necessary, arrange all eight conductors flat in T568B order, trim them square and to the same length, seat them fully in the plug, confirm pin 1 lines up with the white/orange conductor before crimping (a mis-ordered crimp cannot be corrected afterwards), then crimp firmly in one continuous squeeze.</p>`,
  'Cable testing': `
    <p>A cable is not finished when the connector is on — it is finished once it has been tested. A network cable tester checks a Cat6 termination's wire map and catches four faults: an <strong>open</strong> (a pin with no continuity — a conductor not seated, or a break), a <strong>short</strong> (two pins wrongly connected), a <strong>split pair</strong> (wire map looks continuous but conductors come from two different twisted pairs — the trickiest fault, since it can still pass a basic continuity check while causing real intermittent data errors), and a <strong>miswire</strong> (continuity fine, pin order wrong — T568A at one end, T568B at the other).</p>
    <p>Coax terminations are tested differently: a dedicated CCTV/camera tester confirms an actual picture reaches the far end, while a multimeter checks continuity on the centre conductor and shield separately and confirms there's no short between the two — a coax short is a common, quiet cause of a DVR channel showing nothing but a black or frozen screen.</p>`,

  // ---- Module 6 — Installation (Chapter 6) ----
  'Site survey & camera placement': `
    <p>Every professional installation begins with a proper site and risk assessment, not a quick walk-around. A useful rule of thumb: walk the site like the intruder, not the client — approach every boundary and gate from outside the property. Check for overlap at every corner where the perimeter turns. Test the lighting at its worst, not its best — a car park that looks fine at midday can be unusable after dark. Stand at the proposed camera's own height before judging coverage. And rate each area high, medium or low risk, rather than treating every camera as equally important.</p>
    <p>Every survey should end in a written site assessment report: what was recommended, what the client actually agreed to install, and — where those differ — exactly what is left uncovered as a result. That single habit is what separates a technician from a professional installer, and it protects both installer and client if a coverage question ever comes up later.</p>`,
  'Mounting & powering cameras': `
    <p>Two mistakes account for most "the footage is useless" complaints. First, height and angle: roughly 2.4-3 metres with a shallow 15-20° down-angle keeps a face in frame at a useful size while staying out of easy reach — too high with too steep an angle, and a camera only ever sees the tops of heads. Second, backlight: never aim a camera directly at a bright window or the rising/setting sun — the professional fix is choosing an angle so the light source isn't directly behind whoever needs to be identified.</p>
    <p>Every camera needs a solid fixing — brick, block or structural timber, never thin fascia or render alone — and a small downward "drip loop" in the cable before it enters the housing, so water runs off the loop instead of tracking into the connection.</p>`,
  'Weatherproofing & finishing': `
    <p>Every cable entering the equipment cabinet should be labelled at both ends and dressed in tidy bundles, routed so a fault on one cable can be traced without disturbing five others. Outdoor runs need conduit or trunking wherever they're exposed — bare cable stapled to a wall ages and fails far sooner than the same cable properly protected.</p>
    <p>A job is not finished when the last camera is mounted — it is finished once it has been proven to work. Before leaving site: check focus and clarity on every camera at the paid-for resolution; confirm the recorder is actually recording on every channel; test remote viewing from a phone on mobile data, not just site Wi-Fi; and deliberately trigger a motion event on every single camera to confirm it appears in playback. It takes five minutes and catches a mis-configured channel before the client ever finds out the hard way.</p>`,

  // ---- Module 7 — Networking (Chapter 4) ----
  'IP addressing for installers': `
    <p>Four terms come up on every job. <strong>LAN</strong> is the private network confined to one site — every camera, recorder and router on it can talk to each other, but nothing on it is visible to the outside world except through the router. <strong>Ethernet</strong> carries LAN data over Cat5e/Cat6 cable; <strong>Wi-Fi</strong> carries the same data over radio. An <strong>IP address</strong> — four numbers separated by dots, e.g. 192.168.1.10 — identifies one specific device on the network, the way a street address identifies one house.</p>
    <p>Almost every private LAN hands out addresses automatically via DHCP in the 192.168.x.x or 10.x.x.x range; the router itself is usually 192.168.1.1 and is called the gateway. A dynamic IP can change when the router restarts, silently breaking remote viewing — for any device a client needs to reach reliably, assign it a fixed ("static") address, or use the manufacturer's cloud/P2P viewing service instead.</p>`,
  'Switches & PoE budgets': `
    <p>A <strong>PoE switch</strong> carries both data and power to IP cameras over the same cable, sitting between the cameras and the NVR. PoE comes in standardised levels: 802.3af (15.4W at the switch, 12.95W at the camera) for basic fixed cameras; 802.3at/PoE+ (30W/25.5W) for PTZ cameras and IR heaters; 802.3bt Type 3 and Type 4 (up to 90W/71W) for multi-sensor or combined access-control devices.</p>
    <p>A switch advertises its total PoE budget shared across all ports, not per port — add one too many high-draw cameras and the ones nearest the end of the budget reboot at random, which looks exactly like a faulty camera when the real fault is an overloaded switch. Always check three things when choosing a switch: enough ports for today plus growth, a total PoE budget comfortably above the sum of every camera's draw, and a Gigabit uplink port so a fast switch feeding the NVR isn't bottlenecked.</p>`,

  // ---- Module 8 — Remote Viewing (Chapter 8) ----
  'Mobile viewing apps': `
    <p>The moment remote viewing is switched on, the router's gateway to the internet is deliberately opened — which is a genuine security decision, not just a convenience feature. In 2016 the Mirai botnet hijacked hundreds of thousands of ordinary CCTV cameras and DVRs using nothing more than their unchanged factory-default passwords, and used them to knock major websites offline. Changing every default credential on every device, on every job, is the single most important five minutes of any installation.</p>`,
  'P2P, DDNS & static IPs': `
    <p>There are three genuinely different ways to view a system remotely. <strong>P2P cloud relay apps</strong> (Hikvision's Hik-Connect, Dahua's DMSS, EZVIZ) let the recorder "call out" to the manufacturer's cloud, so nothing needs to be opened on the router — the easiest option for most residential and small commercial jobs. <strong>DDNS and port forwarding</strong> gives full control by opening one specific port through the router — but a mis-configured or overly broad rule genuinely exposes the device to the internet, the exact path most Mirai-style attacks used. A <strong>VPN</strong> makes the phone join the site's own network through an encrypted tunnel first, so the recorder itself is never exposed to the public internet at all — the most secure option, worth the extra setup for any client with a real security requirement.</p>`,
  'Securing remote access': `
    <p>Hardening a system before handover, every time: change every default password on the camera, the NVR/DVR and the router; keep firmware updated, since manufacturers patch genuine, published security flaws; disable UPnP on the router, which otherwise lets any device silently open its own port to the internet; and use two-factor authentication wherever the P2P app offers it. For a client with a genuine security requirement — a bank, a legal office, anywhere handling sensitive material — prefer a VPN over an open port, however well the port forwarding is configured.</p>`,

  // ---- Module 9 — AI CCTV (Chapter 9) ----
  'AI analytics overview': `
    <p>Older motion detection compared pixels between frames — anything that changed, from a person to a blowing leaf, triggered an alert. Modern AI-powered analytics instead classify what actually moved, using a trained model that recognises the shape of a person or vehicle specifically and ignores everything else — the same alert system, a small fraction of the false triggers.</p>
    <p>Common features: human/vehicle detection (the foundation — alert only on people or vehicles), line crossing (a virtual trip-wire across the image), intrusion detection (a whole zone rather than one line), face detection and recognition (finding a face vs. matching it to a known list — a meaningfully bigger privacy step), license plate recognition, and abandoned/removed object detection. Real branded examples: Hikvision AcuSense, Dahua WizSense, Uniview's Smart Intrusion Prevention.</p>`,
  'Configuring smart events': `
    <p>The same detection features can run in three places. <strong>Edge AI</strong> (on the camera itself) gives the fastest alerts and keeps working even if the NVR goes offline. <strong>Server AI</strong> (on the NVR) lets one powerful processor serve every connected camera at once, often cheaper per-camera. <strong>Cloud AI</strong> runs the heaviest analytics — like searching recorded footage for "everyone wearing a red jacket" — on remote servers, needing a reliable internet link but able to outperform anything running locally.</p>
    <p>AI genuinely reduces false alarms and turns a wall of footage into a short list of events actually worth attention — but it is not perfect: heavy rain, fog, very low light, or a camera angle that was never fixed properly can all degrade detection accuracy. No AI feature excuses bad fundamentals.</p>`,
  'Face & plate recognition': `
    <p>Face <em>detection</em> simply finds a face in frame for a clearer capture; face <em>recognition</em> goes further and matches it against a known list — a meaningfully bigger privacy and data-protection step, and installers should understand and disclose that distinction to clients rather than treating every AI feature as equivalent. License plate recognition (LPR/ANPR) reads vehicle number plates automatically, logging entries and exits — common at gated sites and car parks.</p>`,

  // ---- Module 10 — Solar CCTV (Chapter 10) ----
  'Solar sizing for CCTV': `
    <p>Sizing a solar system follows the same "do not let it run out" discipline as storage sizing. Panel wattage = daily Wh needed ÷ (peak sun hours × system efficiency): a camera using 120 Wh a day, with 4 peak sun hours and 75% efficiency, needs roughly 40W — rounded up to a 50W panel for headroom. Battery capacity = (daily Wh × autonomy days) ÷ usable depth of discharge: the same camera, with 3 days' autonomy and 80% usable depth of discharge, needs roughly 450 Wh — about 40 Ah at 12V. For a site with weak sun exposure or heavy cloud cover, double both figures, and always validate the real installation with a 7-14 day trial before calling the sizing final.</p>`,
  'Batteries & charge controllers': `
    <p>An <strong>MPPT charge controller</strong> regulates how the panel charges the battery, extracting meaningfully more usable power from the same panel than an older, cheaper PWM controller — worth the extra cost on almost every real job. Modern kits favour <strong>LiFePO4 (lithium iron phosphate)</strong> batteries over older lead-acid, for a longer cycle life (roughly 2,000-5,000 cycles), stable voltage and a much higher usable depth of discharge. A solar panel only performs at its sized capacity if actually sited correctly: angled for the site's hemisphere, clear of shade at any time of day, and mounted as securely and tamper-resistantly as the camera itself.</p>`,
};

// Real, book-grounded multiple-choice / true-false / fill-blank questions,
// replacing the bug where every quiz in the original seed shared the exact
// same four (cabling-only) questions regardless of its actual topic.
export const QUIZ_QUESTIONS = {
  'Quiz: Fundamentals': [
    ['MCQ', 'What does the "closed" in Closed-Circuit Television actually refer to?', ['The camera housing is sealed against weather', 'The signal is confined to a private loop of known, authorised viewers', 'The system works without an internet connection', 'The recorder is locked in a cabinet'], [1]],
    ['MCQ', 'The world’s first CCTV system, built in 1942 at Peenemünde, was installed for what original purpose?', ['To catch thieves in a warehouse', 'To observe a V-2 rocket launch from a safe distance', 'To monitor a bank vault', 'To count factory workers'], [1]],
    ['MCQ', 'Which of the four pillars (People / Property / Process / Proof) would a bank most likely lead with when justifying a CCTV system?', ['People', 'Property', 'Process', 'Proof'], [3]],
    ['TRUE_FALSE', 'A system that shows a live picture on the monitor but is not actually saving footage is still providing real security value.', ['True', 'False'], [1]],
    ['FILL_BLANK', 'Before leaving any completed site, a professional must confirm the system is recording and the footage can be ____ .', [], ['played back', 'reviewed', 'played']],
  ],
  'Quiz: Camera types': [
    ['MCQ', 'Which camera design hides the exact direction it is aimed, thanks to its tinted housing?', ['Bullet', 'Dome', 'Thermal', 'PTZ'], [1]],
    ['MCQ', 'A thermal camera is excellent for perimeter detection in total darkness mainly because it…', ['Has the highest resolution of any camera type', 'Detects heat rather than light, so it needs no illumination at all', 'Can zoom in to read a number plate at night', 'Is the cheapest camera available'], [1]],
    ['MCQ', 'A client wants to identify vehicle number plates at a gate 15 metres away. Which fixed lens would be the wrong choice?', ['8mm', '6mm', '4mm', '2.8mm'], [3]],
    ['TRUE_FALSE', 'A full-colour (ColorVu-type) camera is the same thing as a "wireless" camera.', ['True', 'False'], [1]],
    ['MCQ', 'H.265 compression, compared to the older H.264 standard at the same visual quality, roughly…', ['Doubles the file size', 'Halves the file size', 'Has no effect on file size', 'Only works on analogue cameras'], [1]],
  ],
  'Quiz: Cabling': [
    ['MCQ', 'What is "Siamese" coax cable?', ['A cable rated for direct burial only', 'Coax core bonded to a separate 2-core power cable in one jacket', 'A cable with two centre conductors for redundancy', 'A fibre-optic hybrid cable'], [1]],
    ['MCQ', 'Which BNC termination method gives the best weatherproofing and pull-strength, making it the professional default outdoors?', ['Twist-on', 'Crimp-on', 'Compression', 'Solder-on'], [2]],
    ['MCQ', 'What is the only real difference between the T568A and T568B wiring standards?', ['T568B supports higher speeds', 'The orange and green pairs are swapped at pins 1-2 and 3-6', 'T568A is used only for PoE cameras', 'T568B requires shielded cable'], [1]],
    ['TRUE_FALSE', 'A split-pair fault will always fail a basic continuity check, making it easy to catch.', ['True', 'False'], [1]],
    ['FILL_BLANK', 'Voltage drop on a long analogue power run is fixed almost always by using a thicker cable ____ , not a different power supply.', [], ['gauge', 'wire gauge']],
  ],
  'Quiz: Networking': [
    ['MCQ', 'What is a LAN?', ['The public internet as a whole', 'The private network confined to one site', 'A type of camera lens', 'A cloud viewing app'], [1]],
    ['TRUE_FALSE', 'An analogue camera on a DVR needs its own IP address, exactly like an IP camera does.', ['True', 'False'], [1]],
    ['MCQ', 'A client’s NVR keeps losing its remote-viewing connection every time the router restarts. What is the most likely cause?', ['The NVR has a virus', 'The NVR was assigned a dynamic IP address that changed on restart', 'The cameras are wireless', 'The hard drive is full'], [1]],
    ['MCQ', 'What is the practical difference between a PoE switch and a desktop (unmanaged) switch?', ['A PoE switch is always faster', 'A PoE switch both carries data and delivers power over the cable; a desktop switch only carries data', 'There is no real difference', 'A desktop switch only works with analogue cameras'], [1]],
    ['MCQ', 'Why does a Gigabit uplink port on a PoE switch matter, even if each camera port only runs at 100 Mbps?', ['It looks more professional', 'All the individual camera streams combine at the uplink, which can bottleneck a slower port', 'Gigabit ports use less power', 'It has no real effect'], [1]],
  ],
};

// Assignment briefs, grounded in the book's practical exercises for the
// matching chapter, replacing the generic one-line brief.
export const ASSIGNMENT_BRIEFS = {
  'Storage plan': 'A client needs 6 cameras at 4 Mbps each, with 21 days of continuous retention. Using the sizing formula from this module (bitrate × 86,400 × retention days × channels ÷ 8 ÷ 1,000), calculate the storage required in GB, round up to a real drive size you could actually buy, and explain why you rounded up rather than sizing to the exact number. Submit your calculation and your recommended drive size.',
  'Site survey': 'You are surveying a small warehouse with a single front entrance, a loading bay at the rear that faces due west, and an office with a large east-facing window. For each of the three areas, note: (a) the lighting risk you would check for, and at what time of day; (b) the mounting height and angle you would plan for; (c) how you would confirm, on the day of commissioning, that each camera is genuinely usable rather than merely installed. Submit your survey notes as a short written plan, or photos of a hand-sketched site plan.',
  'Solar CCTV design': 'A client needs a single camera at a remote farm gate, 2 km from the nearest mains power, with an estimated 130 Wh/day draw and 4 peak sun hours available. Calculate: (a) the panel wattage you would size for; (b) the battery capacity for 3 days’ autonomy at 80% usable depth of discharge; (c) what you would check on site before finalising the mounting position; (d) how you would get the footage off site, given there is no existing network at the location. Submit your full calculation and reasoning.',
};
